/* ============================================================
   build.js — generates the two language pages + sitemap.
     node build.js
   src/index.html + js/translations.js  →  index.html      (Greek, main)
                                          en/index.html   (English)
                                          sitemap.xml
   Change SITE_URL if the domain is different.
   ============================================================ */

const fs = require('fs');
const path = require('path');

const SITE_URL = 'https://ootdogslearninglab.gr';
const PHONE = '+306987044459';
const EMAIL = 'nvenetis@ootdogslearninglab.gr';

const translations = require('./js/translations.js');
const template = fs.readFileSync(path.join(__dirname, 'src/index.html'), 'utf8');

const PAGES = {
  el: { file: 'index.html',    url: `${SITE_URL}/`,    base: '',    home: './', otherLang: 'en', otherHref: 'en/' },
  en: { file: 'en/index.html', url: `${SITE_URL}/en/`, base: '../', home: './', otherLang: 'el', otherHref: '../' },
};

const get = (lang, key) => {
  const v = key.split('.').reduce((o, k) => (o != null ? o[k] : undefined), translations[lang]);
  if (v === undefined) throw new Error(`Missing translation "${key}" for ${lang}`);
  return v;
};
const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function structuredData(lang) {
  const t = k => get(lang, k);
  const services = ['s1', 's2', 's3', 's4'].map(s => {
    const offer = {
      '@type': 'Offer',
      itemOffered: { '@type': 'Service', name: t(`services.${s}.title`), description: t(`services.${s}.desc`) },
    };
    if (s === 's1') Object.assign(offer, { price: '0', priceCurrency: 'EUR' });
    return offer;
  });
  return {
    '@context': 'https://schema.org',
    '@type': 'ProfessionalService',
    '@id': `${SITE_URL}/#business`,
    name: 'Out of the Dogs learning lab',
    description: t('seo.description'),
    url: PAGES[lang].url,
    logo: `${SITE_URL}/images/logo-ootd.png`,
    image: `${SITE_URL}/images/og-image.jpg`,
    telephone: PHONE,
    email: EMAIL,
    address: {
      '@type': 'PostalAddress',
      addressLocality: t('seo.locality'),
      addressRegion: t('seo.region'),
      addressCountry: 'GR',
    },
    areaServed: [
      { '@type': 'City', name: t('seo.locality') },
      { '@type': 'City', name: t('seo.city') },
    ],
    founder: { '@type': 'Person', name: t('about.name'), jobTitle: t('seo.jobTitle') },
    knowsAbout: t('seo.knowsAbout'),
    hasOfferCatalog: { '@type': 'OfferCatalog', name: t('seo.catalog'), itemListElement: services },
  };
}

function head(lang) {
  const p = PAGES[lang];
  const t = k => esc(get(lang, k));
  const json = JSON.stringify(structuredData(lang), null, 2).replace(/</g, '\\u003c');
  return `  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${t('seo.title')}</title>
  <meta name="description" content="${t('seo.description')}">
  <link rel="canonical" href="${p.url}">
  <link rel="alternate" hreflang="el" href="${PAGES.el.url}">
  <link rel="alternate" hreflang="en" href="${PAGES.en.url}">
  <link rel="alternate" hreflang="x-default" href="${PAGES.el.url}">
  <meta name="theme-color" content="#2E8385">
  <link rel="icon" href="${p.base}favicon.ico" sizes="any">
  <link rel="icon" type="image/png" href="${p.base}images/favicon-48.png">
  <link rel="apple-touch-icon" href="${p.base}images/apple-touch-icon.png">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Out of the Dogs learning lab">
  <meta property="og:title" content="${t('seo.title')}">
  <meta property="og:description" content="${t('seo.description')}">
  <meta property="og:url" content="${p.url}">
  <meta property="og:image" content="${SITE_URL}/images/og-image.jpg">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta property="og:locale" content="${t('seo.ogLocale')}">
  <meta property="og:locale:alternate" content="${esc(get(p.otherLang, 'seo.ogLocale'))}">
  <meta name="twitter:card" content="summary_large_image">
  <script type="application/ld+json">
${json}
  </script>`;
}

function render(lang) {
  const p = PAGES[lang];
  let html = template
    .replace(/<!--\s*TEMPLATE[\s\S]*?-->\n/, `<!-- Generated by build.js from src/index.html — edit that file instead. -->\n`)
    .replace(/.*<!--TEMPLATE-ONLY-->\n/g, '')
    .replace('{{head}}', head(lang))
    .replace(/{{lang}}/g, lang)
    .replace(/{{base}}/g, p.base)
    .replace(/{{home}}/g, p.home)
    .replace(/{{otherLang}}/g, p.otherLang)
    .replace(/{{otherLangHref}}/g, p.otherHref);

  // Element text: data-i18n (escaped) / data-i18n-html (trusted markup from translations.js)
  html = html.replace(
    /<(\w+)((?:\s[^>]*?)?)\sdata-i18n(-html)?="([^"]+)"([^>]*)>([\s\S]*?)<\/\1>/g,
    (_, tag, before, isHtml, key, after) => {
      const v = get(lang, key);
      return `<${tag}${before} data-i18n${isHtml || ''}="${key}"${after}>${isHtml ? v : esc(v)}</${tag}>`;
    }
  );

  // Attributes: data-i18n-alt / -placeholder / -aria  →  alt / placeholder / aria-label
  const ATTRS = { alt: 'alt', placeholder: 'placeholder', aria: 'aria-label' };
  html = html.replace(/<[^>]+data-i18n-(?:alt|placeholder|aria)="[^"]+"[^>]*>/g, tagStr => {
    for (const [kind, attr] of Object.entries(ATTRS)) {
      const m = tagStr.match(new RegExp(`data-i18n-${kind}="([^"]+)"`));
      if (!m) continue;
      const value = esc(get(lang, m[1]));
      const attrRe = new RegExp(`\\s${attr}="[^"]*"`);
      tagStr = attrRe.test(tagStr)
        ? tagStr.replace(attrRe, ` ${attr}="${value}"`)
        : tagStr.replace(/\s*\/?>$/, ` ${attr}="${value}">`);
    }
    return tagStr;
  });

  const leftover = html.match(/{{\w+}}/);
  if (leftover) throw new Error(`Unreplaced token ${leftover[0]} in ${lang}`);
  return html;
}

for (const lang of Object.keys(PAGES)) {
  const out = path.join(__dirname, PAGES[lang].file);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, render(lang));
  console.log(`✓ ${PAGES[lang].file}`);
}

const today = new Date().toISOString().slice(0, 10);
const alternates = Object.entries(PAGES)
  .map(([l, p]) => `    <xhtml:link rel="alternate" hreflang="${l}" href="${p.url}"/>`)
  .concat(`    <xhtml:link rel="alternate" hreflang="x-default" href="${PAGES.el.url}"/>`)
  .join('\n');
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">
${Object.values(PAGES).map(p => `  <url>
    <loc>${p.url}</loc>
    <lastmod>${today}</lastmod>
${alternates}
  </url>`).join('\n')}
</urlset>
`;
fs.writeFileSync(path.join(__dirname, 'sitemap.xml'), sitemap);
console.log('✓ sitemap.xml');
